### PR TITLE
Add notebook for Google Colab

### PR DESCRIPTION
**Pull request by JanGross**
Adds the source for this Google Colab notebook:  
https://colab.research.google.com/drive/1kfDP4vj0E7REoUZjXqGTk3MP-atJq3cO?usp=sharing

to address #3

### CODE REVIEW

**Comment by AlexRMU** [comment]
So
You can add sample styles, for example before Configuration.
In Configuration, some descriptions are written for videos, but they also work for images. It may also be a little unclear what DOWNSCALE_VIDEO does.
Clearing inputs and outputs is better done automatically, or not at all (that is, so that the videos are not replaced, and a counter is added to them).
It is also better to add the output of the received files before downloading.

**Comment by JanGross** [comment]
> You can add sample styles, for example before Configuration.

Yes, good idea. I will try to incorporate some examples in the next revision.  
I will also rewrite the descriptions.

> Clearing inputs and outputs is better done automatically, or not at all

I found manual clearing to be convenient during testing, but I can remove the cells if necessary. 

> It is also better to add the output of the received files before downloading.

I'm not entirely sure what you mean.

**Comment by AlexRMU** [comment]
> It is also better to add the output of the received files before downloading.
from IPython.display import Image, display
display(Image(i.png))

**Comment by JanGross** [comment]
FYI: Very busy right now but im still on it.

**Pull request closed without merging**
